URL_SERVICE = "https://e34458b7-4588-4f60-8b30-b1e508f3f056.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"